version: '3.8'

services:
  dicom-honeypot:
    build:
      context: .
      dockerfile: Dockerfile.dicom
    container_name: dicom-honeypot
    ports:
      - "11112:11112"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - LOG_LEVEL=INFO
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - dicom-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - dicom-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - dicom-net

  api:
    image: python:3.9-slim
    container_name: dicom-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    command: >
      bash -c "pip install -r requirements.txt && 
      uvicorn simple_api:app --host 0.0.0.0 --port 8000"
    depends_on:
      - elasticsearch
      - dicom-honeypot
    networks:
      - dicom-net

networks:
  dicom-net:
    driver: bridge

volumes:
  es-data:
    driver: local
